services:
  web:
    image: ankur4556/notes-app:latest
    container_name: notes-app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: notes
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db        
      DB_PORT: 3306

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes




  
